src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @ORM\ManyToOne(targetEntity=Event::class, inversedBy="comments")
      * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $event;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Comment::class, inversedBy="replies")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="parent")
     */
    private $replies;

    public function __construct()
    {
        $this->replies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getReplies(): Collection
    {
        return $this->replies;
    }

    public function addReply(self $reply): self
    {
        if (!$this->replies->contains($reply)) {
            $this->replies[] = $reply;
            $reply->setParent($this);
        }

        return $this;
    }

    public function removeReply(self $reply): self
    {
        if ($this->replies->removeElement($reply)) {
            // set the owning side to null (unless already changed)
            if ($reply->getParent() === $this) {
                $reply->setParent(null);
            }
        }

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\EventRepository;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_start;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_end;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="reserve") 
     * @JoinColumn(nullable=true, onDelete="SET NULL")     
     */
    private $users;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="events")
     */
    private $categorie_event;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="event",orphanRemoval=true)
     */
    private $comments;

    

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $artist;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $cp_location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city_location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_location;

    /**
     * @ORM\ManyToMany(targetEntity=Orders::class, mappedBy="reserve")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Event")
     */
    private $reservations;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_place;


    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->categorie_event = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->event_by_artist = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->orderEvents = new ArrayCollection();
        $this->nb_participant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addReserve($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeReserve($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategorieEvent(): Collection
    {
        return $this->categorie_event;
    }

    public function addCategorieEvent(Category $categorieEvent): self
    {
        if (!$this->categorie_event->contains($categorieEvent)) {
            $this->categorie_event[] = $categorieEvent;
        }

        return $this;
    }

    public function removeCategorieEvent(Category $categorieEvent): self
    {
        $this->categorie_event->removeElement($categorieEvent);

        return $this;
    }


    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        $this-> name;

        return $this;
    }

    

    public function getArtist(): ?User
    {
        return $this->artist;
    }

    public function setArtist(?User $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    /**
     * Set the value of images
     *
     * @return  self
     */ 
    public function setImages($images)
    {
        $this->images = $images;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCpLocation(): ?string
    {
        return $this->cp_location;
    }

    public function setCpLocation(string $cp_location): self
    {
        $this->cp_location = $cp_location;

        return $this;
    }

    public function getCityLocation(): ?string
    {
        return $this->city_location;
    }

    public function setCityLocation(string $city_location): self
    {
        $this->city_location = $city_location;

        return $this;
    }

    public function getNameLocation(): ?string
    {
        return $this->name_location;
    }

    public function setNameLocation(string $name_location): self
    {
        $this->name_location = $name_location;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addReserve($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeReserve($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setEvent($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getEvent() === $this) {
                $reservation->setEvent(null);
            }
        }

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    

}

templates/event/_filter.html.twig
{{form_start(form, {attr: {class: 'filter'}})}}
{{ form_row(form.q)}}
<h4>Categories</h4>
{{form_row(form.categories)}}

<h4> Date </h4>
 A partir du {{form_row(form.dateStart)}}
<h4> Prix </h4>
    <div>
    {{form_row(form.min)}} 
    </div>
    <div>
    {{form_row(form.max)}} 
    </div>



{{form_end(form)}}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{app.user.firstname }} Modifie Ton Event {% endblock %}

{% block content %}
<div class="wrapper">
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>


<hr>

</div>
<div class="example-wrapper">
    <h1>Modifier un événement</h1>

  <div class="container container-fluid">
    <div class="row">
      <div class="col-lg-8">
      {{form(form) }}

       {# Vérifier si la route est "event_edit" on affiche les images #}
       {% if app.request.attributes.get('_route') == 'event_edit' %}
       <h2>Images</h2>
       {% for event in events %}
            {% if event.photo| length > 0 %}
              <td><img src="{{ asset('img/' ~ event.photo)}}" width="150" height="150" alt></td>
              
        <div>
         
       {% endif %}
       
       {% endfor %} 
        {% for image in event %}
          <a href="{{path('event_delete_image',{id: image.id}) }}" data-delete data-token="{{csrf_token('delete'~ image.id)}}">Supprimer</a>        
      {% endfor %}
         {% endif %}
        
      </div>
      </div>
      </div>


{% endblock %}

{% block javascripts %}

<script src ="{{ asset('js/images.js')}}"> </script>
</div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} POK | Evenements{% endblock %}




{% block content %}
<div class="sideMargin">
<h1> Evenements à venir </h1>

<div class="event">
 <div class="event1">
<table>
    <thead>
        <tr>
            <th><h2> Filtre</h2></th>
            
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> {% include "event/_filter.html.twig" with {form: form} only %} </td>
        </tr>
    </tbody>
</table>
</div>                                                               
 <div class="event1">
 <table>
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
            {% for event in events %}
            
            <tr class="event-item">
                {% if event.photo | length > 0 %}
                <td><img src="{{ asset('img/' ~ event.photo )}}" width="150" height="150" alt></td>
                {% endif %}
                <td><a href="{{path('show_event', {'id': event.id})}}"> {{event.name}} </a><br></td>
                <td>  {{ event.dateStart| date('d-m-Y') }} {{event.dateEnd | date('d-m-Y')}}  </td> 
                <td> {{event.price}} € </td>
                {% if is_granted('ROLE_ARTISTE') %}
                {% if app.user.id == event.artist.id %}
                <td><a href="{{ path('delete_event',{'id': event.id}) }}">Supprimer</a></td>
                <td><a href="{{ path('event_edit',{'id': event.id}) }}">Modifier</a></td>
                
                {% else %}
                <td> </td>

                <td> </td>
                {% endif %}
                
                {% endif %}
                {# <td><a href="{{ path('cart_add',{'id': event.id}) }}">Reserver</a></td> #}
             </tr>
                
            
        {% endfor %}
        

         {# {% for c in event.categorie_event %}
            <em> {{c.name_category}}</em>
        {% endfor %}  #}
    </tbody>
</table>
{{knp_pagination_render(events)}}
</div>
</div>

</div>
{% endblock %}

  

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} POK | Evenemnt{% endblock %}

{% block content %}

<a href="{{ path('event')}}"> < Retour </a>


          <section class="viewEvent">
          
            {% if event.photo is null %}
            <img class="imgEvent"src="{{ asset('img/imgShowEvent.jpeg' )}}" width="150" height="150" alt>
            {% else %}
          <img class="imgEvent"src="{{ asset('img/' ~ event.photo )}}" width="150" height="150" alt>
               {% endif %} 
          <div class="infoEvent">
               <h1> Evenement {{event.name}} </h1> 
               <small>{{event.cpLocation}} {{event.cityLocation}} {{event.nameLocation}} <br> </small>
               <p style="color: grey ;"> Commence le {{ event.dateStart| date('d-m-Y H:i') }} finis le {{event.dateEnd | date('d-m-Y H:i')}} <br></p>
           <p> Par {{event.artist.pseudo}}</p>
            <a href="{{ path('account_search',{'id': app.user.id}) }}"> <img class="imgArtist"src="{{ asset('img/' ~ event.artist.photo )}}" width="150" height="150" alt></a>
            

              
          <br>
          

                
             <div class="buttonReserve"> <p >  <p>A partir de</p> <p>{{event.price}} € </p></div>
         {{form(cartForm)}}

               <article> {{event.description}} </article>
          </div> 
          
          </section>
               
          <div class="sectionComment">
               <h2> Liste des commentaires</h2>
               {% for comment in event.comments %}
               {% if comment.user.pseudo is null %}
               <p> Anonyme le {{comment.dateCreate | date("d-m-Y H:i")}}</p> 
                <div> {{comment.text| raw}}</div>
                {% else %}
                <p> Publié par {{comment.user.pseudo}} le {{comment.dateCreate | date("d-m-Y H:i")}}</p> 
                <div> {{comment.text| raw}}</div>

                  {# <p><a href="#" data-reply>  SYSTEME DE REPLIS VOIR VIDEO NOUVELLE TECHNO  38MIN19 #}
                    {% endif %}
                    <a href="{{path('deleteComment', {'id': comment.id})}}"><i class="fa-solid fa-trash"></i></a>

               {% endfor %}
               
          </div>
          <div id="ajout-commentaire"> 
          <h2> Ajouter un commentaire </h2>
          {{form(commentForm)}}
          
           </div>
        

{% endblock %}